-- ============================================================================
-- LINKSTAR — 0000: Limpieza de la tabla `orders` legacy
-- ============================================================================
-- Antes de este esquema, el sitio de venta (backend/server.js) ya usaba una
-- tabla public.orders con otra forma (customer_name, items jsonb, sin
-- order_items). Se verificó en producción el 2026-07-31: 0 filas, así que no
-- hay pérdida de datos. 0005_billing_and_orders.sql crea la versión nueva
-- (buyer_*, shipping_address, order_items normalizada).
--
-- `if exists` la vuelve inofensiva en un reset local, donde la tabla legacy
-- nunca existió.
-- ============================================================================
drop table if exists public.orders cascade;
